//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    
    public enum DocumentType : int
    {
        Resume = 1,
        Aadhar = 2,
        VoterId = 3,
        Certificate = 4,
        Marksheet = 5,
        Pan = 6,
        CompanyCertificate = 7,
        Other = 8
    }
}
