//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobSkills = new HashSet<JobSkill>();
            this.JobQualifications = new HashSet<JobQualification>();
            this.UserJobs = new HashSet<UserJob>();
            this.Chats = new HashSet<Chat>();
            this.JobLocations = new HashSet<JobLocation>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleH { get; set; }
        public string ShortDescription { get; set; }
        public string ShortDescriptionH { get; set; }
        public string Description { get; set; }
        public string DescriptionH { get; set; }
        public Nullable<decimal> SalaryMin { get; set; }
        public Nullable<decimal> SalaryMax { get; set; }
        public bool IsMonthly { get; set; }
        public string ExperienceMin { get; set; }
        public string ExperienceMax { get; set; }
        public bool IsPublishd { get; set; }
        public System.DateTime PostedDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public bool IsVerified { get; set; }
        public string Image { get; set; }
        public Nullable<int> NoOfVacancies { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> JobRoleId { get; set; }
        public Nullable<int> JobTypeId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSkill> JobSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobQualification> JobQualifications { get; set; }
        public virtual JobRole JobRole { get; set; }
        public virtual JobType JobType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserJob> UserJobs { get; set; }
        public virtual User User { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobLocation> JobLocations { get; set; }
    }
}
