//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticContent
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleH { get; set; }
        public string ShortDescription { get; set; }
        public string ShortDescriptionH { get; set; }
        public string Description { get; set; }
        public string DescriptionH { get; set; }
        public bool IsPublishd { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string PageName { get; set; }
    }
}
