//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingMaterial()
        {
            this.UserTrainingMaterials = new HashSet<UserTrainingMaterial>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EnrollmentProgramId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Title { get; set; }
        public string TitleH { get; set; }
        public string ShortDescription { get; set; }
        public string ShortDescriptionH { get; set; }
        public string Description { get; set; }
        public string DescriptionH { get; set; }
        public string Link { get; set; }
        public string Attachment { get; set; }
        public string Type { get; set; }
        public System.DateTime PublishDate { get; set; }
        public bool IsPublished { get; set; }
        public string Image { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual EnrollmentProgram EnrollmentProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTrainingMaterial> UserTrainingMaterials { get; set; }
    }
}
