//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Remark { get; set; }
        public string DeviceType { get; set; }
        public string DeviceId { get; set; }
        public string OS { get; set; }
        public string IP { get; set; }
        public string UserAgent { get; set; }
        public string Domain { get; set; }
        public bool IsDeleted { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string Address { get; set; }
        public string DeviceOtherInfo { get; set; }
        public string Data { get; set; }
        public string Error { get; set; }
    
        public virtual User User { get; set; }
    }
}
