//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Mobile2 { get; set; }
        public string Gender { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SpouseName { get; set; }
        public string HusbandName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string State { get; set; }
        public string Photo { get; set; }
        public string CompanyName { get; set; }
        public string Designation { get; set; }
        public string ContactPersonName { get; set; }
        public Nullable<int> NoOfEmployees { get; set; }
        public string About { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Logo { get; set; }
        public string CompanyType { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
    
        public virtual User User { get; set; }
        public virtual City City { get; set; }
    }
}
