//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExperience
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyNameH { get; set; }
        public string YearFrom { get; set; }
        public string YearTo { get; set; }
        public Nullable<int> JobRoleId { get; set; }
        public string Designation { get; set; }
        public string DesignationH { get; set; }
        public string Description { get; set; }
        public string DescriptionH { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsCurrent { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual User User { get; set; }
        public virtual JobRole JobRole { get; set; }
    }
}
